#ifndef __REFLECTION_INCLUDE_H__
#define __REFLECTION_INCLUDE_H__
#include "nim_client_reflection.h"
#include "nim_data_sync_reflection.h"
#include "nim_friend_reflection.h"
#include "nim_global_reflection.h"
#include "nim_msglog_reflection.h"
#include "nim_nos_reflection.h"
#include "nim_online_session_reflection.h"
#include "nim_pass_through_proxy_reflection.h"
#include "nim_plugin_reflection.h"
#include "nim_session_reflection.h"
#include "nim_subscribe_event_reflection.h"
#include "nim_super_team_reflection.h"
#include "nim_system_msg_reflection.h"
#include "nim_talk_reflection.h"
#include "nim_talkex_reflection.h"
#include "nim_team_reflection.h"
#include "nim_tool_reflection.h"
#include "nim_user_reflection.h"
#include "v2client_reflection.h"

#include "chatroom_reflection.h"

#include "qchat_channel_category_reflection.h"
#include "qchat_channel_reflection.h"
#include "qchat_message_reflection.h"
#include "qchat_public_reflection.h"
#include "qchat_role_reflection.h"
#include "qchat_server_reflection.h"
#include "qchat_system_notification_reflection.h"
#endif  // __REFLECTION_INCLUDE_H__